package Repaso

fun main() {

    val numeros  = arrayOf(5,6,8)
    try {
        print(numeros[4])
    }catch (e:Exception){
        println(e)
    }



}
